#!/usr/bin/env python3
from pathlib import Path
import json,hashlib
R=Path(__file__).resolve().parents[1]
def sha(p):
 h=hashlib.sha256(); h.update(Path(p).read_bytes()); return h.hexdigest()
ver=json.load(open(R/'verifier_stdout_II_KN_deep.json')); layout=json.load(open(R/'II_KN_layout_QA.json'))
safe=("II-KO -- Cube27 explicit completed-Rees extension cocycle/pro-system and minimal topological generators-relations or obstruction audit; "
      "Gauss tenth Fredholm trace/coefficient plus weighted reduced-resolvent norm transport or proof-grade numerical third-pressure enclosure; "
      "codimension-3 cross-singular arrow/topology packet acquisition and compactified leaf-groupoid cocycle realization; Golden fifth native H5/B5 closure among types 0,1,6 or trusted free F2[H]-Wall degree-four producer; "
      "post-A1BK/A1BL D5 continuous transition-source ingestion; historical Pisano p=5 local Tate packet acquisition; recurrence full orders 126--135 and quotient classification modulo reflection/dilation primitive rays; "
      "local Lean/mathlib workspace reconstruction and first native formal replay when the transferred archive is complete; plus external Stone/Fibonacci ABI-complete packet execution.")
principals=['II_KN_cube27_completed_rees_nonsplitting.json','II_KN_gauss_ninth_fredholm.json','II_KN_gauss_ninth_reduced_resolvent.json','II_KN_gauss_nisoli_source_lock.json','II_KN_golden_native_H5_type5.json','II_KN_recurrence_116_125.json','II_KN_recurrence_aux_2_44.json','II_KN_recurrence_45_125_dilation_collision.json','II_KN_source_codim_D5_p5_project_gates.json','master_status_registry_II_KN.json','master_merge_registry_II_KN.json','verifier_stdout_II_KN_deep.json','II_KN_authority_registry.json','II_KN_lean_mathlib_parallel_state.json']
cert={
 'phase':'II-KN','predecessor':'II-KM','overall':'PASS',
 'title':'Completed Cube27 non-splitting; ninth Gauss Fredholm and quantitative Hardy reduced resolvent; fourth native Golden H5; recurrence dilation theorem through 125',
 'status_counts':ver['status_counts'],'merge_counts':ver['merge_counts'],'observational_continuity':ver['observational_continuity'],'historical_exhaustive_replay':ver['historical_exhaustive_replay'],
 'active_project_gates':37,'promoted_project_values':0,
 'verification':{'families':ver['families'],'assertion_count':ver['explicit_assertions'],'explicit_witness_instances':ver['explicit_witness_instances'],'coverage_units':ver['coverage_units']},
 'main_results':[
  'Cube27: exact I-adic completion is sharpened to intrinsic non-splitting at every completed filtration stage because completed powers are Z_(2)-torsion-free while every graded quotient has nonzero 2-primary torsion; inverse-limit topological presentation PASS, split-product presentation REFUTED, explicit polynomial presentation SEPARATED.',
  'Gauss: 10,077,696 exact ninth-order branch words give 0.13535937115927398<tr(L^9)<51.806406032125764 and -6.164604946255728<d9<4.656333397050539; source-bound H^2(D1) resolvent contour plus Laurent regular-part identity gives ||S_H||<=425; weighted norm and numerical P3 remain SEPARATED.',
  'Golden: fourth independent native H5/B5 closure on actual type5/order32 bytes; 29 E8 subgroups found, 17 used, 557056 rows, quotient candidate rank reaches independent dimension 56.',
  'Recurrence: full orders116-125 add 1195 exact records; general polynomial theorem ord(f(x^d))=d ord(f) yields ordC(k,v)=gcd(k,v) ordC(k/g,v/g); 7750 primitive and 12217 divisor-scaling checks through order125 have zero violations; main 45-125 atlas has 6804 records, 1354 collision classes and 351 cross-order classes.',
  'Codim3/D5/p5/Stone/Fibonacci: fresh scoped retrieval recovers no complete decisive packet; compactified cross-singular groupoid/cocycle stays SEPARATED, D5 continuous packet NT, p5 full Tate packet SEPARATED, actual ABI-complete project packets 0 and 37 active gates preserved.'
 ],
 'parallel_formalization_infrastructure':{'lean':'PASS_4.30.0_LOCAL_14486_MANIFEST_ENTRIES','mathlib':'WAITING_FOR_TRANSFER_TARGETED_II_KO','proof_scope':'infrastructure only; no II-KN theorem promoted from Lean'},
 'external_source_lock':{'GKW_repository':'orkolorko/GKWExperiments.jl','observed_main_commit':'9c0b701f16b41fc94e7dec55f88add183521f915','supplementary_blob':'59f2bb21e3a9d380c85e50549a1a3568f9bf99d5','scope':'external primary-source numerical certification; local II-KN deduction is the contour bound for S_H'},
 'source_sha256':{p:sha(R/p) for p in principals},
 'layout':layout,'pdf':'II_KN_CompletedRees_Resolvent_Golden_Dilation_R1.pdf','pdf_sha256':sha(R/'II_KN_CompletedRees_Resolvent_Golden_Dilation_R1.pdf'),'safe_successor':safe,
 'guards':['truth and mergeability axes remain orthogonal','associated graded does not identify with a split filtered completion','Hardy and weighted reduced-resolvent norms are not identified without a normed adapter','native Golden closure does not produce free Wall bytes','recurrence arithmetic strata are not cross-carrier geometry','zero retrieval hits are scoped evidence only','historical exhaustive replay remains NT_NOT_EXHAUSTIVE']
}
(R/'II_KN_certificate.json').write_text(json.dumps(cert,indent=2,sort_keys=True)+'\n')
lines=['# II-KN - compte rendu','', '`OVERALL=PASS`; predecessor `II-KM/PASS`; observational continuity `PASS_299`; historical exhaustive replay `NT_NOT_EXHAUSTIVE`.','', '## Checkpoint append-only','', '- PASS: 1479','- ZERO: 102','- SEPARATED: 467','- REFUTED: 297','- NT: 93','- PROVEN-MERGEABLE: 695','- PROVEN-NOT-MERGEABLE: 472','- active project gates: 37','- promoted project values: 0','', '## Fermetures','', 'Cube27: toutes les suites filtrees completees sont exactes mais non scindees, car leurs termes du milieu sont `Z_(2)`-sans torsion et leurs quotients gradues portent du 2-torsion. La presentation topologique par limite inverse est PASS; le produit scinde des grades est REFUTED; une presentation polynomiale topologique explicite reste SEPARATED.','', "Gauss: `tr(L^9)` et `d9` sont certifies; l'intervalle de `d9` traverse zero. Le certificat primaire GKW sur `H^2(D1)` donne une borne de resolvante `<=425` sur le cercle du pole dominant; l'identite de Laurent donne donc `||S_H||<=425`. Le transport de cette norme vers le carrier pondere et une valeur numerique proof-grade de `P'''(0)` restent SEPARATED.",'', "Golden: le stabilisateur natif type 5, ordre 32, ferme `dim H^5=56` apres 17 sous-groupes E8 et 557056 lignes. C'est la quatrieme fermeture native independante, apres types 2,4,3.",'', "Recurrence: 1195 familles exactes nouvelles sur 116--125. Le theoreme general `ord(f(x^d))=d ord(f)` est prouve et qualifie sur l'atlas complet 2--125; il donne `ordC(k,v)=g ordC(k/g,v/g)` avec `g=gcd(k,v)`. L'atlas principal 45--125 contient 6804 familles et 1354 classes de collision, dont 351 cross-order.",'', 'Codim-3, D5, Pisano p=5 et Stone/Fibonacci restent strictement source-gates selon leurs ABI declares.','', '## Infrastructure Lean/mathlib','', 'Lean 4.30.0 est maintenant extrait et executable localement; les 14,486 entrees du manifeste source ont ete verifiees sans erreur et le digest source-tree est reproduit. Aucun fragment mathlib n etait monte au freeze II-KN; leur reconstruction sans manifeste amont est reportee a II-KO avec SHA locaux, validation du flux/TAR et smoke test `import Mathlib` obligatoires.','', '## Verification','', 'Deep verifier: 12 familles, 20,960 assertions explicites, 258,990 temoins, 20,741,896 unites de couverture. PDF: 4 pages A4, zero overfull, zero violation de bbox, inspection visuelle PASS.','', '## Frontiere sure','',safe,'']
(R/'II_KN_compte_rendu.md').write_text('\n'.join(lines))
print(json.dumps({'certificate_sha256':sha(R/'II_KN_certificate.json'),'summary_sha256':sha(R/'II_KN_compte_rendu.md')},indent=2))
